### ISSUE TITLE
Dark Scrollbar in Chrome

### ISSUE THREAD

**Issue by Smail** [onRuntime/instagram-dark-extension#10]
Currently, the scrollbar in Chrome on Instagram uses a white scrollbar, which is especially annoying in the DMs:

![image](https://user-images.githubusercontent.com/44433524/131232332-a91b9bf9-dc9f-467b-ad7e-8ca5c1d3f45c.png)

Can you change it to something like this, please:

![instagram dark scrollbar](https://user-images.githubusercontent.com/44433524/131232185-5e2c8782-c10f-4205-a8c5-53adcfefa64e.png)

Here is the CSS I used to achieve this:

```css
::-webkit-scrollbar {
    width: auto;
    height: auto;
}

::-webkit-scrollbar-button {
    width: 0;
    height: 0;
}

::-webkit-scrollbar-thumb {
    background: #333333;
    border: 1px solid #424242;
}

::-webkit-scrollbar-thumb:hover {
    background: #444444;
}

::-webkit-scrollbar-thumb:active {
    background: #333333;
}

::-webkit-scrollbar-track {
    background: #242424;
}

::-webkit-scrollbar-track:active {
    background: #202020;
}
```
